name: Robot Build Validation

on:
  push:
    branches: 
      - main
      - develop
      - 'infra/**'
      - 'feat/**'
      - 'fix/**'
      - 'test/**'
      - 'docs/**'
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile Robot Code
      run: ./gradlew build
